### PR TITLE
Fix for new BLE 33 R2 board

### PR DESCRIPTION
**Pull request by frankiearzu**
For for the new Arduino BLE 33 Rev 2.    Board pretty similar to Sense, but did not populated the gesture, barometer and other sensor chips.

### CODE REVIEW

**Comment by mattimercu** [comment]
hi can you tell me how to make it work/how to integrate your fix so I can try it with my arduino nano ble r2

**Comment by mattimercu** [comment]
I saw that the change was made to the io.cpp file, but where should I replace it/where is this file located in version 2.2?

**Comment by dlktdr** [comment]
If you log into discord a firmware was posted you can download

**Comment by Iragne** [comment]
Thanks is that possible to add also the link here of the BLE_SR2_v2_21_6876704.zip ?? @dlktdr

**Comment by dlktdr** [comment]
Test Firmware for **Revision 2** Arduino Nano 33 Board Including Sense Variant

GUI - https://drive.google.com/file/d/1-spEWM6YpeYYL2IYvXJItkKlTTSlFNJ_/view?usp=sharing
Firmware -https://drive.google.com/file/d/10CfEIeFCYkZ54mRBg6HcFMFMfSHgCz-m/view?usp=sharing

This is the pre-release. I was not able to get it working on 2.21.

There may still be an issue with this one as well. Please report back.

**Comment by frankiearzu** [comment]
Just tested too. v2.3 works as expected

**Comment by Iragne** [comment]
Me too

**Pull request merged**
